from dragonfly import Choice

def letterChoice(name="letter"):
    return Choice(name, {
        "(alpha|arch)": "a",
        "(bravo|brav) ": "b",
        "(charlie|char) ": "c",
        "(delta|dell) ": "d",
        "(echo|eck) ": "e",
        "(foxtrot|fox) ": "f",
        "(golf) ": "g",
        "(hotel|hark) ": "h",
        "(indigo|ice) ": "i",
        "(julia|jewl) ": "j",
        "(kilo) ": "k",
        "(lie|line) ": "l",
        "(mike) ": "m",
        "(november|noy) ": "n",
        "(Oscar|ork) ": "o",
        "(papa|pom) ": "p",
        "(queen) ": "q",
        "(romeo|rosh) ": "r",
        "(sierra|soy) ": "s",
        "(tango|tay) ": "t",
        "(uniform|unks) ": "u",
        "(victor|van) ": "v",
        "(whiskey|wes) ": "w",
        "(x-ray|trex) ": "x",
        "(yankee|yang) ": "y",
        "(zulu|zooch) ": "z",
        })
